### ISSUE TITLE
Finish glossary page

### ISSUE THREAD

**Issue by jameswillweb2** [jameswillweb2/github-for-web-designers#1]
Dan, can you please finish the glossary.html page? It needs terms and definitions. Thanks!

**Comment by daweston** [comment]
Yep, I’ll get working on this tonight.

**Comment by jameswillweb2** [comment]
Thanks Dan, I appreciate the hard work!

**Comment by daweston** [comment]
Sorry to reopen this, I'll be able to do some of it tonight, but I won't be done till Friday.

**Comment by jameswillweb2** [comment]
That's okay, thanks again.
